package tsp.pro11.reseau;

/**
 *
 * Une énumeration des différents type de contenu possible
 *
 */

public enum Contenu {
	IDENTIFICATION,
	INSCRIPTION,
	REPONSEID,
	DEMANDELISTEEVENT,
	LISTEEVENT,
	AJOUTEVENT,
	PARTICIPATION,
	DEMANDELISTEPARTICIPANTS,
	DEMANDELISTEPARTICIPATIONS,
	LISTEPARTICIPANTS,
	DEMANDENOMBREPARTICIPATION,
	DEMANDENOMBREPARTICIPANT,
	DEMANDENOMBRECREATION,
	ENTIER,
	DESINSCRIPTION,
	SUPRESSIONEVENT,
	DEMANDELISTECREATION;

}
